# Generated by Django 6.0.1 on 2026-01-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsession',
            name='student',
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='status',
            field=models.CharField(choices=[('ANSWERED', 'Answered'), ('NOT_ANSWERED', 'Not Answered'), ('IMPROVEMENT', 'Need Improvement'), ('SKIPPED', 'Skipped')], max_length=20),
        ),
    ]
