# Generated by Django 6.0.1 on 2026-01-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_reviewsession_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsession',
            name='scorecard_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
